// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAluND9rZoaqIBccA0uihgNdCxVcU2WXbw',
    appId: '1:859986520938:web:6a7d9475943cb84a765313',
    messagingSenderId: '859986520938',
    projectId: 'delta-dai-bim',
    authDomain: 'delta-dai-bim.firebaseapp.com',
    storageBucket: 'delta-dai-bim.firebasestorage.app',
    measurementId: 'G-N8F1C1BKE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKMb2TTA_Q5sowVkyQa7s1-SkAfzaiuMY',
    appId: '1:859986520938:android:16d091d967a7d629765313',
    messagingSenderId: '859986520938',
    projectId: 'delta-dai-bim',
    storageBucket: 'delta-dai-bim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSyv0qRh9y5mC2hTCZzjHmpy8ufuugcv8',
    appId: '1:859986520938:ios:b6f2aaad0c188186765313',
    messagingSenderId: '859986520938',
    projectId: 'delta-dai-bim',
    storageBucket: 'delta-dai-bim.firebasestorage.app',
    iosBundleId: 'com.example.deltaDaiBim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSyv0qRh9y5mC2hTCZzjHmpy8ufuugcv8',
    appId: '1:859986520938:ios:b6f2aaad0c188186765313',
    messagingSenderId: '859986520938',
    projectId: 'delta-dai-bim',
    storageBucket: 'delta-dai-bim.firebasestorage.app',
    iosBundleId: 'com.example.deltaDaiBim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAluND9rZoaqIBccA0uihgNdCxVcU2WXbw',
    appId: '1:859986520938:web:7a5f32c02e13eeb0765313',
    messagingSenderId: '859986520938',
    projectId: 'delta-dai-bim',
    authDomain: 'delta-dai-bim.firebaseapp.com',
    storageBucket: 'delta-dai-bim.firebasestorage.app',
    measurementId: 'G-BG85YBTL71',
  );
}
